name: Lint and Unit tests

on: [push]

jobs:
  build:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
      - name: 
        run: |
          node -v
          npm install
      - name: Lint/Test
        run: |
          npm run test-ci

